AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
    - '*.gemspec'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/ClassLength:
  Max: 150

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false 